// vue/src/App.vue
<template>
  <div id="container">
    <DxAutocomplete
        :data-source="dataSource"
        value-expr="Subject"
        :grouped="true"
        label="Search for a task"
        label-mode="floating"
        :show-clear-button="true"
        @value-changed="onValueChanged"
        :wrap-item-text="true"
        :search-timeout="300"
        :max-length="20"
        group-template="group"
        item-template="item"
      >
      <template #group="{data}">
        {{ "Assigned to " + data.key }}
      </template>
      <template #item="{data, index}">
        {{ index + 1 + ". " + data.Subject }}
      </template>
    </DxAutocomplete>
  </div>
</template>

<script>
import { DxAutocomplete } from 'devextreme-vue/autocomplete'
import DataSource from 'devextreme/data/data_source';
import { employeesTasks } from './data.js';

export default {
  components: {
    DxAutocomplete
  },
  data() {
    return {
      dataSource: new DataSource({
        store: {
          type: 'array',
          data: employeesTasks,
          key: 'ID',
        },
        group: 'Assignee',
      }),
    };
  },
  methods: {
    onValueChanged(e) {
      console.log(e.previousValue);
      console.log(e.value);
    }
  }
};
</script>

<style>
#container {
    width: 400px;
}
</style>

// React/src/App.tsx
import { useCallback } from 'react';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import './App.css';
import DataSource from 'devextreme/data/data_source';
import { Autocomplete } from 'devextreme-react/autocomplete';
import type { AutocompleteTypes } from 'devextreme-react/autocomplete';
import { employeesTasks, type Task } from './data';

interface GroupRenderInfo {
  key: string;
  items?: Task[];
}

function App(): JSX.Element {
  const dataSource = new DataSource({
    store: {
      type: 'array',
      data: employeesTasks,
      key: 'ID',
    },
    group: 'Assignee',
  });

  const onValueChanged = useCallback((e: AutocompleteTypes.ValueChangedEvent) => {
    console.log(e.previousValue);
    console.log(e.value);
  }, []);

  const groupRender = useCallback((data: GroupRenderInfo) => (
    <span>
      Assigned to {data.key}
    </span>
  ), []);

  const itemRender = useCallback((data: Task, index: number) => (
    <span>
      {index + 1}. {data.Subject}
    </span>
  ), []);

  return (
    <div id="container">
      <Autocomplete
        dataSource={dataSource}
        valueExpr="Subject"
        grouped={true}
        label="Search for a task"
        labelMode="floating"
        showClearButton={true}
        groupRender={groupRender}
        onValueChanged={onValueChanged}
        itemRender={itemRender}
        wrapItemText={true}
        searchTimeout={300}
        maxLength={20}
      />
    </div>
  );
}

export default App;
